sets.exported={
    main={ name="Vitiation Sword", augments={'Path: C',}},
    sub="Ammurapi Shield",
    ammo="Homiliary",
    head="Atrophy Chapeau +3",
    body={ name="Merlinic Jubbah", augments={'Weapon skill damage +3%','"Store TP"+2','"Treasure Hunter"+2','Mag. Acc.+19 "Mag.Atk.Bns."+19',}},
    hands="Malignance Gloves",
    legs={ name="Carmine Cuisses +1", augments={'Accuracy+20','Attack+12','"Dual Wield"+6',}},
    feet="Malignance Boots",
    neck="Twilight Torque",
    waist="Eschan Stone",
    left_ear="Etiolation Earring",
    right_ear="Malignance Earring",
    left_ring="Ayanmo Ring",
    right_ring="Defending Ring",
    back={ name="Sucellos's Cape", augments={'MND+20','Mag. Acc+20 /Mag. Dmg.+20','Mag. Acc.+10','"Fast Cast"+10','Occ. inc. resist. to stat. ailments+10',}},
}