sets.tp={
	ammo={ name="Coiste Bodhar", augments={'Path: A',}},
	head="Turms Cap +1",
    body={ name="Gleti's Cuirass", augments={'Path: A',}},
    hands="Regal Gloves",
	legs="Malignance Tights",
	feet="Macu. Toe Sh. +3",
	neck={ name="Etoile Gorget +2", augments={'Path: A',}},
	waist={ name="Sailfi Belt +1", augments={'Path: A',}},
	left_ear="Telos Earring",
	right_ear="Sherida Earring",
	left_ring="Roller's Ring",
	right_ring="Gere Ring",
	back={ name="Senuna's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Store TP"+10','Damage taken-5%',}},
}
