sets.tp={
	ammo="Yamarang",
    head="Turms Cap +1",
    body={ name="Gleti's Cuirass", augments={'Path: A',}},
    hands="Regal Gloves",
    legs="Dashing Subligar",
    feet="Gleti's Boots",
    neck={ name="Etoile Gorget +2", augments={'Path: A',}},
    waist={ name="Kentarch Belt +1", augments={'Path: A',}},
    left_ear="Telos Earring",
    right_ear="Sherida Earring",
    left_ring="Roller's Ring",
    right_ring="Chirich Ring +1",
    back="Repulse Mantle",
}
