sets.tp.hybrid={
    ammo="Yamarang",
    head="Malignance Chapeau",
    body="Mummu Jacket +2",
    hands="Malignance Gloves",
    legs="Malignance Tights",
    feet={ name="Horos T. Shoes +3", augments={'Enhances "Closed Position" effect',}},
    neck="Combatant's Torque",
    waist="Eschan Stone",
    left_ear="Telos Earring",
    right_ear="Sherida Earring",
    left_ring="Ilabrat Ring",
    right_ring="Defending Ring",
    back={ name="Senuna's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','Weapon skill damage +10%','Damage taken-5%',}},
}