sets.tp={
    ammo="Yamarang",
    head="Malignance Chapeau",
    body="Malignance Tabard",
    hands="Malignance Gloves",
    legs="Malignance Tights",
    feet={ name="Horos T. Shoes +3", augments={'Enhances "Closed Position" effect',}},
    neck="Combatant's Torque",
    waist="Reiki Yotai",
    left_ear="Telos Earring",
    right_ear="Sherida Earring",
    left_ring="Ilabrat Ring",
    -- right_ring="Epona's Ring",
    right_ring="Apate Ring",
    back={ name="Toetapper Mantle", augments={'"Store TP"+3','"Dual Wield"+5','Weapon skill damage +1%',}},
}