sets.ws={
	ammo={ name="Coiste Bodhar", augments={'Path: A',}},
	head="Maculele Tiara +3",
	body={ name="Nyame Mail", augments={'Path: B',}},
	hands="Maxixi Bangles +3",
	legs={ name="Nyame Flanchard", augments={'Path: B',}},
	feet={ name="Nyame Sollerets", augments={'Path: B',}},
	neck={ name="Etoile Gorget +2", augments={'Path: A',}},
	waist={ name="Kentarch Belt +1", augments={'Path: A',}},
	left_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
	-- right_ear="Odr Earring",
	right_ear="Macu. Earring +1",
	left_ring="Ilabrat Ring",
	right_ring="Regal Ring",
	back={ name="Senuna's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','Weapon skill damage +10%','Damage taken-5%',}},
}
