sets.idle={
    ammo="Homiliary",
    head={ name="Peda. M.Board +2", augments={'Enh. "Altruism" and "Focalization"',}},
    body="Shamash Robe",
    hands="Volte Gloves",
    legs="Volte Brais",
    feet="Crier's Gaiters",
    neck="Loricate Torque +1",
    waist="Eschan Stone",
    left_ear="Etiolation Earring",
    right_ear="Eabani Earring",
    left_ring={ name="Gelatinous Ring +1", augments={'Path: A',}},
    right_ring="Defending Ring",
    back={ name="Lugh's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','"Mag.Atk.Bns."+10','Damage taken-5%',}},
}
