sets.midcast.elemental.vagary={
	main={ name="Bunzi's Rod", augments={'Path: A',}},
	sub="Ammurapi Shield",
	ammo="Staunch Tathlum",
	head=empty,
	body="Acad. Gown +3",
	hands=empty,
	legs=empty,
	feet="Acad. Loafers +3",
	neck={ name="Loricate Torque +1", augments={'Path: A',}},
	waist="Carrier's Sash",
	left_ear="Etiolation Earring",
	right_ear={ name="Odnowa Earring +1", augments={'Path: A',}},
	left_ring={ name="Gelatinous Ring +1", augments={'Path: A',}},
	right_ring="Defending Ring",
	back={ name="Lugh's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','"Mag.Atk.Bns."+10','Damage taken-5%',}},
}
