sets.midcast.elemental={
	ammo="Pemphredo Tathlum",
	head={ name="Peda. M.Board +3", augments={'Enh. "Altruism" and "Focalization"',}},
	body="Acad. Gown +3",
	hands={ name="Amalric Gages +1", augments={'INT+12','Mag. Acc.+20','"Mag.Atk.Bns."+20',}},
	legs={ name="Peda. Pants +3", augments={'Enhances "Tabula Rasa" effect',}},
	-- feet={ name="Agwu's Pigaches", augments={'Path: A',}},
	feet="Arbatel Loafers +2",
	neck="Mizu. Kubikazari",
	waist="Sacro Cord",
	left_ear="Regal Earring",
	right_ear="Malignance Earring",
	left_ring="Freke Ring",
	right_ring="Mujin Band",
	back={ name="Lugh's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','"Mag.Atk.Bns."+10','Damage taken-5%',}},
}
