sets.midcast.elemental={
	ammo="Pemphredo Tathlum",
	head="Arbatel Bonnet +3",
	body="Acad. Gown +3",
	hands={ name="Agwu's Gages", augments={'Path: A',}},
	legs="Arbatel Pants +3",
	feet={ name="Agwu's Pigaches", augments={'Path: A',}},
	neck={ name="Argute Stole +2", augments={'Path: A',}},
	waist="Sacro Cord",
	left_ear="Regal Earring",
	right_ear="Malignance Earring",
	left_ring="Freke Ring",
	right_ring="Mujin Band",
	back={ name="Lugh's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','INT+10','"Mag.Atk.Bns."+10','Damage taken-5%',}},
}
