sets.naked={
    main="Chocobo Wand",
    sub="Genmei Shield",
    ammo="Staunch Tathlum +1",
    head="Wh. Rarab Cap +1",
    body="Carpenter's Smock",
    hands="Carpenter's Gloves",
    legs="Shedir Seraweels",
    feet="Crier's Gaiters",
    neck="Bathy Choker +1",
    waist="Plat. Mog. Belt",
    left_ear="Digni. Earring",
    right_ear={ name="Odnowa Earring +1", augments={'Path: A',}},
    left_ring="Chirich Ring +1",
    right_ring="Defending Ring",
    back="Perimede Cape",
}