sets.tp={
    ammo="Ginsen",
    head="Flam. Zucchetto +2",
    body={ name="Agoge Lorica +3", augments={'Enhances "Aggressive Aim" effect',}},
    hands={ name="Agoge Mufflers +3", augments={'Enhances "Mighty Strikes" effect',}},
    legs="Flamma Dirs +2",
    feet="Flam. Gambieras +2",
    neck="Combatant's Torque",
    waist="Ioskeha Belt +1",
    left_ear="Suppanomimi",
    right_ear="Telos Earring",
    left_ring="Niqmaddu Ring",
    right_ring="Petrov Ring",
    back={ name="Cichol's Mantle", augments={'Accuracy+20 Attack+20','"Dbl.Atk."+10',}},
}
