sets.ws.accuracy={
	ammo="Knobkierrie",
	head={ name="Agoge Mask +3", augments={'Enhances "Savagery" effect',}},
	body="Pumm. Lorica +3",
	hands={ name="Sakpata's Gauntlets", augments={'Path: A',}},
	legs="Pumm. Cuisses +3",
	feet="Pumm. Calligae +3",
	neck={ name="War. Beads +2", augments={'Path: A',}},
	waist="Grunfeld Rope",
	left_ear={ name="Schere Earring", augments={'Path: A',}},
	right_ear={ name="Boii Earring +2", augments={'System: 1 ID: 1676 Val: 0','Accuracy+19','Mag. Acc.+19','Crit.hit rate+7','STR+13 VIT+13',}},
	left_ring="Niqmaddu Ring",
	right_ring="Regal Ring",
	back={ name="Cichol's Mantle", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%',}},
}
