sets.ws.multihit={
	ammo={ name="Coiste Bodhar", augments={'Path: A',}},
	head="Flam. Zucchetto +2",
	body={ name="Sakpata's Plate", augments={'Path: A',}},
	hands={ name="Sakpata's Gauntlets", augments={'Path: A',}},
	legs="Pumm. Cuisses +3",
	feet="Pumm. Calligae +3",
	neck="Fotia Gorget",
	waist="Fotia Belt",
	left_ear="Telos Earring",
	right_ear={ name="Boii Earring +1", augments={'System: 1 ID: 1676 Val: 0','Accuracy+13','Mag. Acc.+13','Crit.hit rate+4',}},
	left_ring="Niqmaddu Ring",
	right_ring="Regal Ring",
	back={ name="Cichol's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','"Dbl.Atk."+10','Phys. dmg. taken-10%',}},
}
