sets.ws.singlehit={
    ammo="Knobkierrie",
    head="Flam. Zucchetto +2",
    body={ name="Agoge Lorica +3", augments={'Enhances "Aggressive Aim" effect',}},
    hands={ name="Agoge Mufflers +3", augments={'Enhances "Mighty Strikes" effect',}},
    legs="Flamma Dirs +2",
    feet="Sulev. Leggings +2",
    neck={ name="Warrior's Beads", augments={'Path: A',}},
    waist="Grunfeld Rope",
    left_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
    right_ear="Thrud Earring",
    left_ring="Niqmaddu Ring",
    right_ring="Regal Ring",
    back={ name="Cichol's Mantle", augments={'STR+20','Accuracy+20 Attack+20','"Dbl.Atk."+10','Phys. dmg. taken-10%',}},
}
