sets.ws.singlehit={
    ammo="Knobkierrie",
    head={ name="Agoge Mask +2", augments={'Enhances "Savagery" effect',}},
    body="Pumm. Lorica +2",
    hands={ name="Odyssean Gauntlets", augments={'Weapon skill damage +3%','STR+14','Accuracy+14',}},
    legs="Flamma Dirs +2",
    feet="Sulev. Leggings +2",
    neck={ name="War. Beads +2", augments={'Path: A',}},
    waist="Grunfeld Rope",
    left_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
    right_ear="Thrud Earring",
    left_ring="Niqmaddu Ring",
    right_ring="Regal Ring",
    back={ name="Cichol's Mantle", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%',}},
}
