sets.ws={
    ammo="Knobkierrie",
    head="Flam. Zucchetto +2",
    body="Nzingha Cuirass",
    hands="Flam. Manopolas +2",
    legs="Flamma Dirs +2",
    feet="Sulev. Leggings +2",
    neck="Unmoving Collar +1",
    waist="Ioskeha Belt",
    left_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
    right_ear="Ishvara Earring",
    left_ring="Flamma Ring",
    right_ring="Regal Ring",
    back="Agema Cape",
}