sets.ws={
	ammo="Knobkierrie",
	head={ name="Agoge Mask +4", augments={'Enhances "Savagery" effect',}},
	body={ name="Nyame Mail", augments={'Path: B',}},
	hands="Boii Mufflers +3",
	legs="Boii Cuisses +3",
	feet={ name="Nyame Sollerets", augments={'Path: B',}},
	neck={ name="War. Beads +2", augments={'Path: A',}},
	waist={ name="Sailfi Belt +1", augments={'Path: A',}},
	left_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
	right_ear="Thrud Earring",
	left_ring="Sroda Ring",
	right_ring="Ephramad's Ring",
	back={ name="Cichol's Mantle", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%',}},
}
