sets.tp={
	ammo={ name="Coiste Bodhar", augments={'Path: A',}},
	head="Kasuga Kabuto +2",
	body="Kasuga Domaru +2",
	hands={ name="Nyame Gauntlets", augments={'Path: B',}},
	legs="Kasuga Haidate +2",
	feet={ name="Nyame Sollerets", augments={'Path: B',}},
	neck="Combatant's Torque",
	waist="Ioskeha Belt +1",
	left_ear="Telos Earring",
	right_ear="Crep. Earring",
	left_ring="Niqmaddu Ring",
	right_ring="Chirich Ring +1",
	back={ name="Takaha Mantle", augments={'STR+1','"Zanshin"+1','"Store TP"+3',}},
}
