sets.weakws={
	ammo="Staunch Tathlum +1",
	head="Flam. Zucchetto +2",
	body="Emet Harness +1",
	hands="Wakido Kote +3",
	legs={ name="Sakonji Haidate +3", augments={'Enhances "Shikikoyo" effect',}},
	feet={ name="Sak. Sune-Ate +2", augments={'Enhances "Meikyo Shisui" effect',}},
	neck="Combatant's Torque",
	waist="Ioskeha Belt +1",
	left_ear="Dedition Earring",
    right_ear="Telos Earring",
	left_ring={ name="Gelatinous Ring +1", augments={'Path: A',}},
	right_ring="Defending Ring",
	back={ name="Smertrios's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','"Store TP"+10','Phys. dmg. taken-10%',}},
}