sets.weakws={
	ammo="Staunch Tathlum",
	head="Flam. Zucchetto +2",
	body="Emet Harness +1",
	hands="Wakido Kote +3",
	legs={ name="Sakonji Haidate +1", augments={'Enhances "Shikikoyo" effect',}},
	feet={ name="Sak. Sune-Ate +1", augments={'Enhances "Meikyo Shisui" effect',}},
	neck="Combatant's Torque",
	waist="Ioskeha Belt +1",
	left_ear="Telos Earring",
	right_ear="Crep. Earring",
	left_ring={ name="Gelatinous Ring +1", augments={'Path: A',}},
	right_ring="Defending Ring",
	back={ name="Takaha Mantle", augments={'STR+1','"Zanshin"+1','"Store TP"+3',}},
}