sets.ws={
    ammo="Knobkierrie",
    head="Nyame Helm",
    body="Sakonji Domaru +3",
    hands="Flam. Manopolas +2",
    legs="Wakido Haidate +3",
    feet="Flam. Gambieras +2",
    neck="Caro Necklace",
    waist="Grunfeld Rope",
    left_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
    right_ear="Thrud Earring",
    left_ring="Niqmaddu Ring",
    right_ring="Regal Ring",
    back={ name="Smertrios's Mantle", augments={'STR+20','Accuracy+20 Attack+20','Weapon skill damage +10%','Damage taken-5%',}},
}
