sets.tp={
	ammo={ name="Coiste Bodhar", augments={'Path: A',}},
	head={ name="Sakpata's Helm", augments={'Path: A',}},
	body={ name="Sakpata's Plate", augments={'Path: A',}},
	hands={ name="Sakpata's Gauntlets", augments={'Path: A',}},
	legs={ name="Nyame Flanchard", augments={'Path: B',}},
	feet={ name="Nyame Sollerets", augments={'Path: B',}},
	neck="Combatant's Torque",
	waist="Ioskeha Belt +1",
	left_ear="Telos Earring",
	right_ear="Crep. Earring",
	left_ring="Niqmaddu Ring",
	right_ring="Petrov Ring",
	back={ name="Ankou's Mantle", augments={'VIT+20','Accuracy+20 Attack+20','VIT+10','Weapon skill damage +10%',}},
}
