sets.ws={
    ammo="Knobkierrie",
    head="Sakpata's Helm",
    body="Sakpata's Plate",
    hands={ name="Odyssean Gauntlets", augments={'Weapon skill damage +3%','STR+14','Accuracy+14',}},
    legs={ name="Valorous Hose", augments={'Accuracy+6','Weapon skill damage +4%','VIT+14',}},
    feet="Sulev. Leggings +2",
    neck="Unmoving Collar +1",
    waist="Fotia Belt",
    left_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
    right_ear="Thrud Earring",
    left_ring="Niqmaddu Ring",
    right_ring="Regal Ring",
    back={ name="Mecisto. Mantle", augments={'Cap. Point+50%','MP+13','Mag. Acc.+1','DEF+5',}},
}
