sets.tp={
	ammo={ name="Coiste Bodhar", augments={'Path: A',}},
	head="Hjarrandi Helm",
	body="Hjarrandi Breast.",
	hands={ name="Nyame Gauntlets", augments={'Path: B',}},
	legs={ name="Nyame Flanchard", augments={'Path: B',}},
	feet={ name="Nyame Sollerets", augments={'Path: B',}},
	neck="Combatant's Torque",
	waist="Ioskeha Belt +1",
	left_ear="Telos Earring",
	right_ear="Sherida Earring",
	left_ring="Niqmaddu Ring",
	right_ring="Chirich Ring +1",
	back={ name="Brigantia's Mantle", augments={'STR+20','Accuracy+20 Attack+20','STR+10','"Dbl.Atk."+10','Phys. dmg. taken-10%',}},
}
