sets.ws={
	ammo={ name="Coiste Bodhar", augments={'Path: A',}},
	head="Flam. Zucchetto +2",
	body={ name="Nyame Mail", augments={'Path: B',}},
	hands="Sulev. Gauntlets +2",
	legs={ name="Nyame Flanchard", augments={'Path: B',}},
	feet="Flam. Gambieras +2",
	neck="Fotia Gorget",
	waist="Fotia Belt",
	left_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
	right_ear="Sherida Earring",
	left_ring="Niqmaddu Ring",
	right_ring="Regal Ring",
	back={ name="Brigantia's Mantle", augments={'STR+20','Accuracy+20 Attack+20','STR+10','"Dbl.Atk."+10','Phys. dmg. taken-10%',}},
}
