sets.exported={
    main="Trishula",
    sub="Utu Grip",
    ammo="Knobkierrie",
    head="Flam. Zucchetto +2",
    body="Nzingha Cuirass",
    hands="Flam. Manopolas +2",
    legs="Flamma Dirs +2",
    feet="Flam. Gambieras +2",
    neck="Fotia Gorget",
    waist="Fotia Belt",
    left_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
    right_ear="Sherida Earring",
    left_ring="Niqmaddu Ring",
    right_ring="Regal Ring",
    back="Agema Cape",
}