sets.fastcast={
    ammo="Sapience Orb",
    head={ name="Amalric Coif +1", augments={'INT+12','Mag. Acc.+25','Enmity-6',}},
    body={ name="Merlinic Jubbah", augments={'Weapon skill damage +3%','"Store TP"+2','"Treasure Hunter"+2','Mag. Acc.+19 "Mag.Atk.Bns."+19',}},
    hands="Jhakri Cuffs +2",
    legs="Volte Brais",
    feet={ name="Merlinic Crackows", augments={'"Mag.Atk.Bns."+24','"Dbl.Atk."+1','Mag. Acc.+15 "Mag.Atk.Bns."+15',}},
    neck="Voltsurge Torque",
    waist="Embla Sash",
    left_ear="Etiolation Earring",
    right_ear="Malignance Earring",
    left_ring="Jhakri Ring",
    right_ring="Kishar Ring",
    back={ name="Taranus's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','"Mag.Atk.Bns."+10','Damage taken-5%',}},
}
