sets.midcast.elemental={
	ammo="Pemphredo Tathlum",
	head={ name="Nyame Helm", augments={'Path: B',}},
	body="Spaekona's Coat +3",
	hands={ name="Agwu's Gages", augments={'Path: A',}},
	legs={ name="Arch. Tonban +3", augments={'Increases Elemental Magic debuff time and potency',}},
	feet={ name="Agwu's Pigaches", augments={'Path: A',}},
	neck="Mizu. Kubikazari",
	waist="Sacro Cord",
	left_ear="Regal Earring",
	right_ear="Malignance Earring",
	left_ring="Freke Ring",
	right_ring="Mujin Band",
	back={ name="Taranus's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','"Mag.Atk.Bns."+10','Damage taken-5%',}},
}
