sets.midcast.enfeebling={
	ammo="Pemphredo Tathlum",
	head={ name="Amalric Coif +1", augments={'INT+12','Mag. Acc.+25','Enmity-6',}},
	body="Spaekona's Coat +3",
	hands={ name="Agwu's Gages", augments={'Path: A',}},
	legs={ name="Nyame Flanchard", augments={'Path: B',}},
	feet={ name="Agwu's Pigaches", augments={'Path: A',}},
	neck={ name="Src. Stole +2", augments={'Path: A',}},
	waist="Luminary Sash",
	left_ear="Regal Earring",
	right_ear="Malignance Earring",
	left_ring={ name="Metamor. Ring +1", augments={'Path: A',}},
	right_ring="Kishar Ring",
	back={ name="Taranus's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','"Mag.Atk.Bns."+10','Damage taken-5%',}},
}
