sets.tp.empyreanam={
    ammo={ name="Coiste Bodhar", augments={'Path: A',}},
    head="Skulker's Bonnet +3",
    body="Skulker's Vest +3",
    hands="Skulk. Armlets +3",
    legs="Skulk. Culottes +3",
    feet="Skulk. Poulaines +3",
    neck={ name="Asn. Gorget +2", augments={'Path: A',}},
    waist="Reiki Yotai",
    left_ear="Suppanomimi",
    right_ear="Sherida Earring",
    left_ring="Epona's Ring",
    right_ring="Gere Ring",
    back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Store TP"+10','Damage taken-5%',}},
}