sets.tp.hybrid={
	ammo="Yamarang",
	head="Malignance Chapeau",
	body="Malignance Tabard",
	hands="Malignance Gloves",
	legs="Malignance Tights",
	feet="Malignance Boots",
	neck={ name="Asn. Gorget +2", augments={'Path: A',}},
	waist="Reiki Yotai",
	left_ear="Telos Earring",
	right_ear="Sherida Earring",
	left_ring="Ilabrat Ring",
	right_ring="Defending Ring",
	back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Store TP"+10','Mag. Evasion+15',}},
}
