sets.ws.accuracy={
    ammo="C. Palug Stone",
    head="Skulker's Bonnet +3",
    body="Skulker's Vest +2",
    hands="Skulk. Armlets +2",
    legs="Skulk. Culottes +3",
    feet="Skulk. Poulaines +3",
    neck={ name="Asn. Gorget +2", augments={'Path: A',}},
    waist={ name="Kentarch Belt +1", augments={'Path: A',}},
    left_ear="Odr Earring",
    right_ear="Sherida Earring",
    left_ring="Chirich Ring +1",
    right_ring="Ephramad's Ring",
    back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Store TP"+10','Damage taken-5%',}},
}