sets.ws={
	ammo="C. Palug Stone",
	head="Pill. Bonnet +3",
	body="Skulker's Vest +3",
	hands={ name="Nyame Gauntlets", augments={'Path: B',}},
	legs={ name="Plun. Culottes +3", augments={'Enhances "Feint" effect',}},
	feet={ name="Nyame Sollerets", augments={'Path: B',}},
	neck={ name="Asn. Gorget +2", augments={'Path: A',}},
	waist={ name="Kentarch Belt +1", augments={'Path: A',}},
	left_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
	right_ear="Skulk. Earring +2",
	left_ring="Ilabrat Ring",
	right_ring="Regal Ring",
	back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','Weapon skill damage +10%','"Regen"+5',}},
}
