sets.ws={
    ammo="C. Palug Stone",
    head="Pill. Bonnet +3",
    body={ name="Herculean Vest", augments={'Attack+27','Weapon skill damage +4%','DEX+3','Accuracy+11',}},
    hands="Meg. Gloves +2",
    legs="Mummu Kecks +2",
    feet={ name="Herculean Boots", augments={'"Store TP"+1','Pet: Attack+2 Pet: Rng.Atk.+2','Weapon skill damage +6%','Accuracy+7 Attack+7',}},
    neck="Fotia Gorget",
    waist="Fotia Belt",
    left_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
    right_ear="Sherida Earring",
    left_ring="Ilabrat Ring",
    right_ring="Regal Ring",
    back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','Weapon skill damage +10%',}},
}
