sets.idle={
    ammo="Ginsen",
    head="Malignance Chapeau",
    body="Malignance Tabard",
    hands="Malignance Gloves",
    legs="Malignance Tights",
    feet="Crier's Gaiters",
    neck="Sanctity Necklace",
    waist="Black Belt",
    left_ear="Etiolation Earring",
    right_ear="Odnowa Earring +1",
    eft_ring="Gelatinous Ring +1",
    right_ring="Defending Ring",
    back="Agema Cape",
}
