sets.ws={
    ammo="Knobkierrie",
    head="Mummu Bonnet +2",
    body="Mummu Jacket +2",
    hands="Malignance Gloves",
    legs="Hiza. Hizayoroi +2",
    feet={ name="Herculean Boots", augments={'Accuracy+22','Weapon skill damage +4%','DEX+7','Attack+3',}},
    neck="Fotia Gorget",
    waist="Fotia Belt",
    left_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
    right_ear="Sherida Earring",
    left_ring="Apate Ring",
    right_ring="Regal Ring",
    back="Agema Cape",
}
