sets.ws={
	ammo={ name="Coiste Bodhar", augments={'Path: A',}},
	head={ name="Mpaca's Cap", augments={'Path: A',}},
	body={ name="Nyame Mail", augments={'Path: B',}},
	hands={ name="Nyame Gauntlets", augments={'Path: B',}},
	legs={ name="Nyame Flanchard", augments={'Path: B',}},
	feet={ name="Nyame Sollerets", augments={'Path: B',}},
	neck="Fotia Gorget",
	waist="Fotia Belt",
	left_ear="Odr Earring",
	right_ear="Sherida Earring",
	left_ring="Niqmaddu Ring",
	right_ring="Regal Ring",
	back={ name="Segomo's Mantle", augments={'STR+20','Accuracy+20 Attack+20','STR+10','"Dbl.Atk."+10',}},
}
