sets.hpdown={
	ammo="Staunch Tathlum",
	head=empty,
	body=empty,
	hands=empty,
	legs=empty,
	feet=empty,
	neck={ name="Loricate Torque +1", augments={'Path: A',}},
	waist=empty,
	left_ear=empty,
	right_ear=empty,
	left_ring={ name="Metamor. Ring +1", augments={'Path: A',}},
	right_ring="Defending Ring",
	back=empty,
}
