sets.idle.hybrid={
    ammo="Homiliary",
    head="Aya. Zucchetto +2",
    body="Shamash Robe",
    hands="Aya. Manopolas +2",
    legs="Aya. Cosciales +2",
    feet="Aya. Gambieras +2",
    neck="Loricate Torque +1",
    waist="Eschan Stone",
    left_ear="Etiolation Earring",
    right_ear="Eabani Earring",
    left_ring="Ayanmo Ring",
    right_ring="Defending Ring",
    back={ name="Alaunus's Cape", augments={'MND+20','Eva.+20 /Mag. Eva.+20','Mag. Evasion+10','"Cure" potency +10%','Occ. inc. resist. to stat. ailments+10',}},
}
