sets.idle={
    ammo="Homiliary",
    head="Inyanga Tiara +2",
    body="Shamash Robe",
    hands="Volte Gloves",
    legs="Volte Brais",
    feet="Crier's Gaiters",
    neck="Loricate Torque +1",
    waist="Eschan Stone",
    left_ear="Etiolation Earring",
    right_ear="Eabani Earring",
    left_ring="Gelatinous Ring +1",
    right_ring="Defending Ring",
    back={ name="Alaunus's Cape", augments={'MND+20','Eva.+20 /Mag. Eva.+20','Mag. Evasion+10','"Cure" potency +10%','Occ. inc. resist. to stat. ailments+10',}},
}
