sets.midcast.mb={
    ammo="Pemphredo Tathlum",
    head={ name="Chironic Hat", augments={'Attack+30','CHR+1','Phalanx +4','Mag. Acc.+11 "Mag.Atk.Bns."+11',}},
    body="Shamash Robe",
    hands="Volte Gloves",
    legs="Volte Brais",
    feet="Bunzi's Sabots",
    neck="Mizu. Kubikazari",
    waist="Eschan Stone",
    left_ear="Regal Earring",
    right_ear="Malignance Earring",
    left_ring="Freke Ring",
    right_ring="Mujin Band",
    back={ name="Alaunus's Cape", augments={'MND+20','Eva.+20 /Mag. Eva.+20','Mag. Evasion+10','Haste+10','Occ. inc. resist. to stat. ailments+10',}},
}
