sets.midcast.enfeebling={
	ammo="Pemphredo Tathlum",
	head="Theophany Cap +3",
	body="Theo. Bliaut +3",
	hands="Theophany Mitts +4",
	legs={ name="Chironic Hose", augments={'Mag. Acc.+22 "Mag.Atk.Bns."+22','MND+12','Mag. Acc.+10','"Mag.Atk.Bns."+1',}},
	feet="Theo. Duckbills +4",
	neck="Erra Pendant",
	waist={ name="Obstin. Sash", augments={'Path: A',}},
	left_ear="Regal Earring",
	right_ear="Ebers Earring +1",
	left_ring={ name="Metamor. Ring +1", augments={'Path: A',}},
	right_ring="Kishar Ring",
	back={ name="Alaunus's Cape", augments={'MND+20','Accuracy+20 Attack+20','MND+10','Weapon skill damage +10%',}},
}
