sets.midcast.enfeebling={
	ammo="Pemphredo Tathlum",
	head="Theophany Cap +3",
	body="Theo. Bliaut +3",
	hands="Theophany Mitts +3",
	legs={ name="Chironic Hose", augments={'Mag. Acc.+22 "Mag.Atk.Bns."+22','MND+12','Mag. Acc.+10','"Mag.Atk.Bns."+1',}},
	feet="Theo. Duckbills +3",
	neck="Erra Pendant",
	waist="Luminary Sash",
	left_ear="Regal Earring",
	right_ear={ name="Ebers Earring +1", augments={'System: 1 ID: 1676 Val: 0','Accuracy+15','Mag. Acc.+15','Damage taken-5%',}},
	left_ring={ name="Metamor. Ring +1", augments={'Path: A',}},
	right_ring="Kishar Ring",
	back={ name="Alaunus's Cape", augments={'MND+20','Accuracy+20 Attack+20','MND+10','Weapon skill damage +10%',}},
}
