sets.midcast.healing={
	ammo="Staunch Tathlum",
	head="Ebers Cap +1",
	body="Ebers Bliaut +1",
	hands="Theophany Mitts +3",
	legs="Ebers Pant. +2",
	feet={ name="Piety Duckbills +3", augments={'Enhances "Afflatus Solace" effect',}},
	neck={ name="Clr. Torque +2", augments={'Path: A',}},
	waist="Luminary Sash",
	left_ear="Mendi. Earring",
	right_ear="Glorious Earring",
	left_ring="Lebeche Ring",
	right_ring="Naji's Loop",
	back={ name="Alaunus's Cape", augments={'MND+20','Eva.+20 /Mag. Eva.+20','Mag. Evasion+10','Haste+10','Occ. inc. resist. to stat. ailments+10',}},
}
