sets.tp={
    ammo="Hasty Pinion +1",
    head="Nyame Helm",
    body="Ayanmo Corazza +2",
    hands="Aya. Manopolas +2",
    legs="Nyame Flanchard",
    feet={ name="Bunzi's Sabots", augments={'Path: A',}},
    neck="Combatant's Torque",
    waist="Grunfeld Rope",
    left_ear="Telos Earring",
    right_ear="Cessance Earring",
    left_ring="Ilabrat Ring",
    right_ring="Petrov Ring",
    back={ name="Alaunus's Cape", augments={'MND+20','Accuracy+20 Attack+20','MND+10','Weapon skill damage +10%',}},
}
