sets.tp={
    ammo="Hasty Pinion +1",
    head={ name="Nyame Helm", augments={'Path: B',}},
    body={ name="Nyame Mail", augments={'Path: B',}},
    hands={ name="Nyame Gauntlets", augments={'Path: B',}},
    legs={ name="Nyame Flanchard", augments={'Path: B',}},
    feet={ name="Nyame Sollerets", augments={'Path: B',}},
    neck="Combatant's Torque",
    waist="Grunfeld Rope",
    left_ear="Telos Earring",
    right_ear="Cessance Earring",
    left_ring="Ilabrat Ring",
    right_ring="Petrov Ring",
    back={ name="Alaunus's Cape", augments={'MND+20','Accuracy+20 Attack+20','MND+10','Weapon skill damage +10%',}},
}
