sets.ws.accuracy={
    ammo="Oshasha's Treatise",
    head="Ebers Cap +3",
    body="Ebers Bliaut +3",
    hands="Ebers Mitts +3",
    legs="Ebers Pant. +3",
    feet="Ebers Duckbills +3",
    neck="Combatant's Torque",
    waist="Eschan Stone",
    left_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
    right_ear="Malignance Earring",
    left_ring="Rufescent Ring",
    right_ring={ name="Metamor. Ring +1", augments={'Path: A',}},
    back={ name="Alaunus's Cape", augments={'MND+20','Accuracy+20 Attack+20','MND+10','Weapon skill damage +10%',}},
}