sets.ws.singlehit={
    ammo="Oreiad's Tathlum",
    head="Nyame Helm",
    body={ name="Piety Briault +3", augments={'Enhances "Benediction" effect',}},
    hands={ name="Piety Mitts +3", augments={'Enhances "Martyr" effect',}},
    legs="Nyame Flanchard",
    feet={ name="Piety Duckbills +3", augments={'Enhances "Afflatus Solace" effect',}},
    neck={ name="Clr. Torque +1", augments={'Path: A',}},
    waist="Luminary Sash",
    left_ear="Ishvara Earring",
    right_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
    left_ring="Ilabrat Ring",
    right_ring="Rufescent Ring",
    back={ name="Alaunus's Cape", augments={'MND+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%',}},
}
