sets.ws={
	ammo="Crepuscular Pebble",
	head={ name="Nyame Helm", augments={'Path: B',}},
	body={ name="Bunzi's Robe", augments={'Path: A',}},
	hands={ name="Nyame Gauntlets", augments={'Path: B',}},
	legs={ name="Nyame Flanchard", augments={'Path: B',}},
	feet={ name="Nyame Sollerets", augments={'Path: B',}},
	-- neck={ name="Clr. Torque +2", augments={'Path: A',}},
	neck="Rep. Plat. Medal",
	waist="Luminary Sash",
	left_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
	right_ear="Ishvara Earring",
	left_ring={ name="Metamor. Ring +1", augments={'Path: A',}},
	right_ring="Ephramad's Ring",
	back={ name="Alaunus's Cape", augments={'MND+20','Accuracy+20 Attack+20','MND+10','Weapon skill damage +10%',}},
}
