sets.ws={
    ammo="Hasty Pinion +1",
    head={ name="Piety Cap +2", augments={'Enhances "Devotion" effect',}},
    body={ name="Piety Briault +3", augments={'Enhances "Benediction" effect',}},
    hands="Aya. Manopolas +2",
    legs="Aya. Cosciales +2",
    feet={ name="Piety Duckbills +2", augments={'Enhances "Afflatus Solace" effect',}},
    neck="Fotia Gorget",
    waist="Fotia Belt",
    left_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
    right_ear="Cessance Earring",
    left_ring="Ilabrat Ring",
    right_ring="Rufescent Ring",
    back={ name="Alaunus's Cape", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Crit.hit rate+10',}},
}
