sets.tp={
    range={ name="Linos", augments={'Accuracy+20','"Dbl.Atk."+2','Quadruple Attack +3',}},
    head={ name="Bunzi's Hat", augments={'Path: A',}},
    body={ name="Bunzi's Robe", augments={'Path: A',}},
    hands="Regal Gloves",
    legs="Dashing Subligar",
    feet="Fili Cothurnes +3",
    neck={ name="Bard's Charm +2", augments={'Path: A',}},
    waist={ name="Kentarch Belt +1", augments={'Path: A',}},
    left_ear="Telos Earring",
    right_ear="Fili Earring +2",
    left_ring="Roller's Ring",
    right_ring="Chirich Ring +1",
    back="Repulse Mantle",
}