sets.tp={
    ammo="Regal Gem",
    head="Malignance Chapeau",
    body={ name="Viti. Tabard +3", augments={'Enhances "Chainspell" effect',}},
    hands="Aya. Manopolas +2",
    legs="Atrophy Tights +3",
    feet="Malignance Boots",
    neck="Bathy Choker +1",
    waist="Hachirin-no-Obi",
    left_ear="Andoaa Earring",
    right_ear="Regal Earring",
    left_ring="Chirich Ring +1",
    right_ring="Chirich Ring +1",
    right_ring="Jhakri Ring",
    back={ name="Ghostfyre Cape", augments={'Enfb.mag. skill +7','Enha.mag. skill +9','Mag. Acc.+2','Enh. Mag. eff. dur. +18',}},
}
