sets.idle={
    head="Azimuth Hood +1",
    body="Shamash Robe",
    hands="Geo. Mitaines +3",
    legs="Volte Brais",
    feet="Azimuth Gaiters +1",
    neck="Twilight Torque",
    waist="Isa Belt",
    left_ear="Etiolation Earring",
    right_ear="Odnowa Earring +1",
    left_ring="Gelatinous Ring +1",
    -- left_ring="Fortified Ring",
    right_ring="Defending Ring",
    back={ name="Nantosuelta's Cape", augments={'HP+60','Eva.+20 /Mag. Eva.+20','Pet: "Regen"+10','Pet: "Regen"+5',}},
}