sets.idle={
	head="Azimuth Hood +3",
	-- body="Zendik Robe",
	body="Azimuth Coat +3",
	hands="Geo. Mitaines +3",
	legs={ name="Nyame Flanchard", augments={'Path: B',}},
	-- feet="Geo. Sandals +3",
	feet={ name="Bagua Sandals +4", augments={'Enhances "Radial Arcana" effect',}},
	-- neck={ name="Loricate Torque +1", augments={'Path: A',}},
	neck={ name="Bagua Charm +2", augments={'Path: A',}},
	waist="Carrier's Sash",
	left_ear="Etiolation Earring",
	right_ear={ name="Odnowa Earring +1", augments={'Path: A',}},
	left_ring={ name="Gelatinous Ring +1", augments={'Path: A',}},
	right_ring="Defending Ring",
	back={ name="Nantosuelta's Cape", augments={'HP+60','Eva.+20 /Mag. Eva.+20','Pet: "Regen"+10','Pet: "Regen"+5',}},
}
