sets.naked={
    main="Chocobo Wand",
    sub="Genmei Shield",
    head="Wh. Rarab Cap +1",
    body="Carpenter's Smock",
    hands="Carpenter's Gloves",
    legs="Shedir Seraweels",
    feet="Crier's Gaiters",
    neck={ name="Loricate Torque +1", augments={'Path: A',}},
    waist="Embla Sash",
    left_ear="Etiolation Earring",
    right_ear="Loquac. Earring",
    left_ring="Kishar Ring",
    right_ring="Defending Ring",
    back={ name="Mecisto. Mantle", augments={'Cap. Point+49%','CHR+1','DEF+7',}},
}
