sets.precast.quickdraw={
    ammo="Hauksbok Bullet",
    head="Malignance Chapeau",
    body={ name="Lanun Frac +3", augments={'Enhances "Loaded Deck" effect',}},
    hands="Malignance Gloves",
    legs="Malignance Tights",
    feet={ name="Lanun Bottes +4", augments={'Enhances "Wild Card" effect',}},
    neck="Iskur Gorget",
    waist="Reiki Yotai",
    left_ear="Dedition Earring",
    right_ear="Telos Earring",
    left_ring="Ilabrat Ring",
    right_ring="Dingir Ring",
    back={ name="Camulus's Mantle", augments={'AGI+20','Mag. Acc+20 /Mag. Dmg.+20','AGI+10','Weapon skill damage +10%','Damage taken-5%',}},
}