sets.tp={
	head="Malignance Chapeau",
	body="Malignance Tabard",
	hands="Malignance Gloves",
	legs="Malignance Tights",
	feet="Malignance Boots",
	neck="Iskur Gorget",
	-- waist="Reiki Yotai",
	waist={ name="Kentarch Belt +1", augments={'Path: A',}},
	-- left_ear="Suppanomimi",
	left_ear="Telos Earring",
	right_ear={ name="Chas. Earring +2", augments={'System: 1 ID: 1676 Val: 0','Accuracy+17','Mag. Acc.+17','Crit.hit rate+6','STR+9 AGI+9',}},
	left_ring="Ilabrat Ring",
	right_ring="Chirich Ring +1",
	back="Null Shawl",
}
