sets.level60={
    main="Chatoyant Staff",
    sub="Enki Strap",
    ammo="Pemphredo Tathlum",
    head="Warlock's Chapeau",
    body="Atrophy Tabard +3",
    hands="Volte Gloves",
    legs="Volte Brais",
    feet={ name="Bunzi's Sabots", augments={'Path: A',}},
    neck={ name="Dls. Torque +2", augments={'Path: A',}},
    waist="Sacro Cord",
    left_ear="Malignance Earring",
    right_ear="Regal Earring",
    left_ring="Naji's Loop",
    right_ring={ name="Metamor. Ring +1", augments={'Path: A',}},
    back={ name="Sucellos's Cape", augments={'MND+20','Mag. Acc+20 /Mag. Dmg.+20','Mag. Acc.+10','Haste+10','Occ. inc. resist. to stat. ailments+10',}},
}