sets.midcast.elemental={
	ammo="Pemphredo Tathlum",
	head="Leth. Chappel +2",
	body="Lethargy Sayon +2",
	hands={ name="Amalric Gages +1", augments={'INT+12','Mag. Acc.+20','"Mag.Atk.Bns."+20',}},
	legs="Leth. Fuseau +2",
	feet={ name="Vitiation Boots +3", augments={'Immunobreak Chance',}},
	neck="Mizu. Kubikazari",
	waist="Sacro Cord",
	left_ear="Regal Earring",
	right_ear="Malignance Earring",
	left_ring="Freke Ring",
	right_ring="Mujin Band",
	back={ name="Sucellos's Cape", augments={'MND+20','Mag. Acc+20 /Mag. Dmg.+20','Mag. Acc.+10','Haste+10','Occ. inc. resist. to stat. ailments+10',}},
}
