sets.midcast.enfeeblingpotency={
	ammo="Regal Gem",
	head={ name="Viti. Chapeau +3", augments={'Enfeebling Magic duration','Magic Accuracy',}},
	body="Lethargy Sayon +1",
	hands="Leth. Ganth. +2",
	legs={ name="Chironic Hose", augments={'Mag. Acc.+22 "Mag.Atk.Bns."+22','MND+12','Mag. Acc.+10','"Mag.Atk.Bns."+1',}},
	feet={ name="Vitiation Boots +3", augments={'Immunobreak Chance',}},
	neck={ name="Dls. Torque +2", augments={'Path: A',}},
	waist="Luminary Sash",
	left_ear="Regal Earring",
	right_ear="Snotra Earring",
	left_ring={ name="Metamor. Ring +1", augments={'Path: A',}},
	right_ring="Kishar Ring",
	back={ name="Sucellos's Cape", augments={'MND+20','Mag. Acc+20 /Mag. Dmg.+20','Mag. Acc.+10','Haste+10','Occ. inc. resist. to stat. ailments+10',}},
}
