sets.midcast.enhancing={
	ammo="Regal Gem",
	head="Leth. Chappel +2",
	body="Lethargy Sayon +2",
	hands="Atrophy Gloves +3",
	legs="Leth. Fuseau +2",
	feet="Leth. Houseaux +2",
	neck={ name="Dls. Torque +2", augments={'Path: A',}},
	waist="Embla Sash",
	left_ear="Mimir Earring",
	right_ear="Andoaa Earring",
	left_ring="Lebeche Ring",
	right_ring="Kishar Ring",
	back={ name="Ghostfyre Cape", augments={'Enfb.mag. skill +1','Enha.mag. skill +2','Enh. Mag. eff. dur. +20',}},
}
