sets.midcast.darkmagic={
    -- range="Ullr",
    ammo="Regal Gem",
    head="Leth. Chappel +3",
    body="Atrophy Tabard +4",
    hands="Leth. Ganth. +3",
    legs="Leth. Fuseau +3",
    feet="Leth. Houseaux +3",
    neck="Erra Pendant",
    -- waist={ name="Obstin. Sash", augments={'Path: A',}},
    waist="Cornelia's Belt",
    left_ear="Regal Earring",
    right_ear="Snotra Earring",
    left_ring="Kishar Ring",
    right_ring="Stikini Ring +1",
    back={ name="Sucellos's Cape", augments={'MND+20','Mag. Acc+20 /Mag. Dmg.+20','Mag. Acc.+10','Haste+10','Occ. inc. resist. to stat. ailments+10',}},
}