sets.midcast.elemental={
	ammo="Pemphredo Tathlum",
	head="Leth. Chappel +3",
	body="Lethargy Sayon +3",
	hands={ name="Agwu's Gages", augments={'Path: A',}},
	legs="Leth. Fuseau +3",
	feet={ name="Vitiation Boots +3", augments={'Immunobreak Chance',}},
	neck="Mizu. Kubikazari",
	waist="Sacro Cord",
	left_ear="Regal Earring",
	right_ear="Malignance Earring",
	left_ring="Freke Ring",
	right_ring="Mujin Band",
	back={ name="Sucellos's Cape", augments={'MND+20','Mag. Acc+20 /Mag. Dmg.+20','Mag. Acc.+10','Haste+10','Occ. inc. resist. to stat. ailments+10',}},
}
