sets.midcast.enhancing={
	ammo="Regal Gem",
	head="Leth. Chappel +3",
	body="Lethargy Sayon +3",
	hands="Atrophy Gloves +4",
	legs="Leth. Fuseau +3",
	feet="Leth. Houseaux +3",
	neck={ name="Dls. Torque +2", augments={'Path: A',}},
	waist="Embla Sash",
	left_ear="Mimir Earring",
	right_ear="Leth. Earring +1",
	left_ring="Lebeche Ring",
	right_ring="Kishar Ring",
	back={ name="Ghostfyre Cape", augments={'Enfb.mag. skill +1','Enha.mag. skill +2','Enh. Mag. eff. dur. +20',}},
}
