sets.midcast.enfeebling={
    ammo="Regal Gem",
    head={ name="Viti. Chapeau +3", augments={'Enfeebling Magic duration','Magic Accuracy',}},
    body="Atrophy Tabard +3",
    hands="Leth. Gantherots +1",
    legs={ name="Chironic Hose", augments={'Mag. Acc.+22 "Mag.Atk.Bns."+22','MND+12','Mag. Acc.+10','"Mag.Atk.Bns."+1',}},
    feet={ name="Vitiation Boots +1", augments={'Immunobreak Chance',}},
    neck="Dls. Torque +1",
    waist="Luminary Sash",
    left_ear="Regal Earring",
    right_ear="Snotra Earring",
    left_ring="Ayanmo Ring",
    right_ring="Kishar Ring",
    back={ name="Sucellos's Cape", augments={'MND+20','Mag. Acc+20 /Mag. Dmg.+20','Mag. Acc.+10','"Fast Cast"+10','Occ. inc. resist. to stat. ailments+10',}},
}
