sets.tp={
	ammo={ name="Coiste Bodhar", augments={'Path: A',}},
	head={ name="Bunzi's Hat", augments={'Path: A',}},
	body="Malignance Tabard",
	hands="Malignance Gloves",
	legs="Malignance Tights",
	feet="Malignance Boots",
	neck="Anu Torque",
	waist="Reiki Yotai",
	left_ear="Suppanomimi",
	right_ear="Sherida Earring",
	left_ring="Ilabrat Ring",
	right_ring="Chirich Ring +1",
	back={ name="Sucellos's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','"Dbl.Atk."+10','Phys. dmg. taken-10%',}},
}
