sets.midcast.enfeebling={
    ammo="Pemphredo Tathlum",
    head="Hachiya Hatsu. +3",
    body="Hattori Ningi +3",
    hands={ name="Mochizuki Tekko +3", augments={'Enh. "Ninja Tool Expertise" effect',}},
    legs="Hattori Hakama +3",
    feet="Hattori Kyahan +3",
    neck="Incanter's Torque",
    waist="Eschan Stone",
    left_ear="Digni. Earring",
    right_ear={ name="Hattori Earring +2", augments={'System: 1 ID: 1676 Val: 0','Accuracy+16','Mag. Acc.+16','"Store TP"+6','DEX+7 AGI+7',}},
    left_ring={ name="Metamor. Ring +1", augments={'Path: A',}},
    right_ring="Stikini Ring +1",
    back={ name="Andartia's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','"Fast Cast"+10','Spell interruption rate down-10%',}},
}