sets.tp={
	ammo="Date Shuriken",
	head="Malignance Chapeau",
	body="Malignance Tabard",
	hands="Malignance Gloves",
	legs="Malignance Tights",
	feet="Malignance Boots",
	neck={ name="Ninja Nodowa +2", augments={'Path: A',}},
	waist="Olseni Belt",
	left_ear="Crep. Earring",
	right_ear={ name="Hattori Earring +2", augments={'System: 1 ID: 1676 Val: 0','Accuracy+16','Mag. Acc.+16','"Store TP"+6','DEX+7 AGI+7',}},
	left_ring="Gere Ring",
	right_ring="Regal Ring",
	back={ name="Andartia's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','"Fast Cast"+10','Spell interruption rate down-10%',}},
}
