sets.tp={
    -- ammo="Yamarang",
    ammo="Happo Shuriken",
    head="Malignance Chapeau",
    body={ name="Mochi. Chainmail +3", augments={'Enhances "Sange" effect',}},
    hands="Malignance Gloves",
    legs="Malignance Tights",
    feet="Malignance Boots",
    neck="Combatant's Torque",
    waist="Reiki Yotai",
    left_ear="Suppanomimi",
    right_ear="Telos Earring",
    left_ring="Ilabrat Ring",
    right_ring="Gere Ring",
    back={ name="Andartia's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','"Fast Cast"+10','Spell interruption rate down-10%',}},
}
