sets.ws={
    ammo="C. Palug Stone",
    head="Malignance Chapeau",
    body={ name="Herculean Vest", augments={'Accuracy+7','Weapon skill damage +4%','DEX+11',}},
    hands="Malignance Gloves",
    legs="Hiza. Hizayoroi +2",
    feet={ name="Herculean Boots", augments={'Weapon skill damage +5%','DEX+7',}},
    neck="Caro Necklace",
    waist="Grunfeld Rope",
    left_ear="Telos Earring",
    right_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
    left_ring="Ilabrat Ring",
    right_ring="Regal Ring",
    back={ name="Andartia's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','"Fast Cast"+10','Spell interruption rate down-10%',}},
}
