sets.tp={
	ammo={ name="Coiste Bodhar", augments={'Path: A',}},
	head={ name="Sakpata's Helm", augments={'Path: A',}},
	body={ name="Sakpata's Plate", augments={'Path: A',}},
	hands={ name="Sakpata's Gauntlets", augments={'Path: A',}},
	legs={ name="Nyame Flanchard", augments={'Path: B',}},
	feet={ name="Nyame Sollerets", augments={'Path: B',}},
	neck="Combatant's Torque",
	waist={ name="Sailfi Belt +1", augments={'Path: A',}},
	left_ear="Telos Earring",
	right_ear="Chev. Earring +2",
	left_ring="Petrov Ring",
	right_ring="Defending Ring",
	back="Null Shawl",
}