sets.tp={
	range={ name="Linos", augments={'Accuracy+20','"Dbl.Atk."+2','Quadruple Attack +3',}},
    head={ name="Bunzi's Hat", augments={'Path: A',}},
    body={ name="Bunzi's Robe", augments={'Path: A',}},
    hands={ name="Bunzi's Gloves", augments={'Path: A',}},
    legs="Fili Rhingrave +3",
    feet={ name="Nyame Sollerets", augments={'Path: B',}},
    neck={ name="Bard's Charm +2", augments={'Path: A',}},
    waist={ name="Sailfi Belt +1", augments={'Path: A',}},
    left_ear="Crep. Earring",
    right_ear="Telos Earring",
    left_ring="Ilabrat Ring",
    right_ring="Chirich Ring +1",
    back="Null Shawl",
}
