sets.tp={
	range={ name="Linos", augments={'Accuracy+20','"Dbl.Atk."+2','Quadruple Attack +3',}},
	head={ name="Bunzi's Hat", augments={'Path: A',}},
	body={ name="Bihu Jstcorps. +3", augments={'Enhances "Troubadour" effect',}},
	hands={ name="Gazu Bracelets +1", augments={'Path: A',}},
	legs={ name="Nyame Flanchard", augments={'Path: B',}},
	feet={ name="Nyame Sollerets", augments={'Path: B',}},
	neck={ name="Bard's Charm +2", augments={'Path: A',}},
	waist="Reiki Yotai",
	left_ear="Suppanomimi",
	right_ear="Telos Earring",
	left_ring="Ilabrat Ring",
	right_ring="Chirich Ring +1",
	back={ name="Intarabus's Cape", augments={'CHR+20','Mag. Acc+20 /Mag. Dmg.+20','CHR+10','"Fast Cast"+10','Phys. dmg. taken-10%',}},
}
