sets.ws.accuracy={
    range={ name="Linos", augments={'Accuracy+20','"Dbl.Atk."+2','Quadruple Attack +3',}},
    head={ name="Bunzi's Hat", augments={'Path: A',}},
    body="Fili Hongreline +2",
    hands="Fili Manchettes +2",
    legs="Fili Rhingrave +2",
    feet="Fili Cothurnes +2",
    neck={ name="Bard's Charm +2", augments={'Path: A',}},
    waist="Reiki Yotai",
    left_ear="Suppanomimi",
    right_ear="Telos Earring",
    left_ring="Ilabrat Ring",
    right_ring="Chirich Ring +1",
    back={ name="Intarabus's Cape", augments={'CHR+20','Mag. Acc+20 /Mag. Dmg.+20','CHR+10','Haste+10','Phys. dmg. taken-10%',}},
}