sets.ws={
	range={ name="Linos", augments={'Accuracy+14 Attack+14','Weapon skill damage +3%','DEX+7',}},
	head={ name="Nyame Helm", augments={'Path: B',}},
	body={ name="Nyame Mail", augments={'Path: B',}},
	hands={ name="Nyame Gauntlets", augments={'Path: B',}},
	legs={ name="Nyame Flanchard", augments={'Path: B',}},
	feet={ name="Nyame Sollerets", augments={'Path: B',}},
	neck={ name="Bard's Charm +2", augments={'Path: A',}},
	waist={ name="Kentarch Belt +1", augments={'Path: A',}},
	left_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
	right_ear="Fili Earring +2",
	left_ring="Epaminondas's Ring",
	right_ring="Ephramad's Ring",
	back={ name="Intarabus's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','Weapon skill damage +10%','Damage taken-5%',}},
}
