sets.idle={
	ammo="Staunch Tathlum +1",
	head={ name="Nyame Helm", augments={'Path: B',}},
	body="Hashishin Mintan +3",
	hands="Hashi. Bazu. +3",
	legs={ name="Carmine Cuisses +1", augments={'Accuracy+20','Attack+12','"Dual Wield"+6',}},
	feet={ name="Nyame Sollerets", augments={'Path: B',}},
	neck={ name="Loricate Torque +1", augments={'Path: A',}},
	waist="Carrier's Sash",
	left_ear="Etiolation Earring",
	right_ear={ name="Odnowa Earring +1", augments={'Path: A',}},
	left_ring={ name="Gelatinous Ring +1", augments={'Path: A',}},
	right_ring="Defending Ring",
	back="Null Shawl",
}
