sets.idle={
	ammo="Staunch Tathlum",
	head={ name="Nyame Helm", augments={'Path: B',}},
	body="Shamash Robe",
	hands={ name="Nyame Gauntlets", augments={'Path: B',}},
	legs={ name="Carmine Cuisses +1", augments={'Accuracy+20','Attack+12','"Dual Wield"+6',}},
	feet={ name="Nyame Sollerets", augments={'Path: B',}},
	neck={ name="Loricate Torque +1", augments={'Path: A',}},
	waist="Flume Belt",
	left_ear="Etiolation Earring",
	right_ear={ name="Odnowa Earring +1", augments={'Path: A',}},
	left_ring={ name="Gelatinous Ring +1", augments={'Path: A',}},
	right_ring="Defending Ring",
	back={ name="Rosmerta's Cape", augments={'Mag. Acc+20 /Mag. Dmg.+20','"Mag.Atk.Bns."+10',}},
}
