sets.midcast.elemental={
	ammo={ name="Ghastly Tathlum +1", augments={'Path: A',}},
	head="Hashishin Kavuk +3",
	body="Hashishin Mintan +3",
	hands="Hashi. Bazu. +3",
	legs="Hashishin Tayt +3",
	feet="Hashi. Basmak +3",
	neck="Sibyl Scarf",
	waist="Orpheus's Sash",
	left_ear="Regal Earring",
	right_ear="Friomisi Earring",
	left_ring={ name="Metamor. Ring +1", augments={'Path: A',}},
	right_ring="Stikini Ring +1",
	back={ name="Rosmerta's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','INT+10','"Mag.Atk.Bns."+10','Phys. dmg. taken-10%',}},
}
