sets.midcast.elemental={
	ammo="Pemphredo Tathlum",
	head={ name="Nyame Helm", augments={'Path: B',}},
	body="Hashishin Mintan +2",
	hands="Hashi. Bazu. +2",
	legs="Hashishin Tayt +2",
	feet="Hashi. Basmak +2",
	neck="Sanctity Necklace",
	waist="Orpheus's Sash",
	left_ear="Regal Earring",
	right_ear="Friomisi Earring",
	left_ring={ name="Metamor. Ring +1", augments={'Path: A',}},
	right_ring="Kishar Ring",
	back={ name="Rosmerta's Cape", augments={'Mag. Acc+20 /Mag. Dmg.+20','"Mag.Atk.Bns."+10',}},
}
