sets.tp={
	ammo={ name="Coiste Bodhar", augments={'Path: A',}},
	head="Malignance Chapeau",
	body="Malignance Tabard",
	hands="Malignance Gloves",
	legs="Malignance Tights",
	feet="Malignance Boots",
	neck="Combatant's Torque",
	waist="Reiki Yotai",
	left_ear="Suppanomimi",
	right_ear="Crep. Earring",
	left_ring="Ilabrat Ring",
	right_ring="Epona's Ring",
	back={ name="Rosmerta's Cape", augments={'Mag. Acc+20 /Mag. Dmg.+20','"Mag.Atk.Bns."+10',}},
}
