sets.ws.multihit={
	ammo={ name="Coiste Bodhar", augments={'Path: A',}},
	head="Malignance Chapeau",
	body={ name="Nyame Mail", augments={'Path: B',}},
	hands={ name="Adhemar Wrist. +1", augments={'Accuracy+20','Attack+20','"Subtle Blow"+8',}},
	legs={ name="Nyame Flanchard", augments={'Path: B',}},
	feet={ name="Nyame Sollerets", augments={'Path: B',}},
	neck={ name="Mirage Stole +2", augments={'Path: A',}},
	waist="Fotia Belt",
	left_ear="Odr Earring",
	right_ear="Hashi. Earring +1",
	left_ring="Ilabrat Ring",
	right_ring="Ephramad's Ring",
	back={ name="Rosmerta's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','"Store TP"+10','Damage taken-5%',}},
}
