sets.ws={
    ammo={ name="Coiste Bodhar", augments={'Path: A',}},
    head="Jhakri Coronal +2",
    body={ name="Herculean Vest", augments={'Accuracy+7','Weapon skill damage +4%','DEX+11',}},
    hands="Jhakri Cuffs +2",
    legs="Jhakri Slops +2",
    feet={ name="Herculean Boots", augments={'Weapon skill damage +5%','DEX+7',}},
    neck="Caro Necklace",
    waist="Grunfeld Rope",
    left_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
    right_ear="Ishvara Earring",
    left_ring="Ilabrat Ring",
    right_ring="Rufescent Ring",
    back={ name="Rosmerta's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','"Mag.Atk.Bns."+10','Phys. dmg. taken-10%',}},
}
