sets.ws={
	ammo="Oshasha's Treatise",
	head="Hashishin Kavuk +3",
	body={ name="Nyame Mail", augments={'Path: B',}},
	hands={ name="Nyame Gauntlets", augments={'Path: B',}},
	legs={ name="Nyame Flanchard", augments={'Path: B',}},
	feet={ name="Nyame Sollerets", augments={'Path: B',}},
	neck={ name="Mirage Stole +2", augments={'Path: A',}},
	waist={ name="Sailfi Belt +1", augments={'Path: A',}},
	left_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
	right_ear="Ishvara Earring",
	left_ring={ name="Metamor. Ring +1", augments={'Path: A',}},
	right_ring="Ephramad's Ring",
	back={ name="Rosmerta's Cape", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%','Damage taken-5%',}},
}
